name: bring_me
description: "Bring Me is a mobile game where players are tasked with finding and bringing specific items to the host. The game features a dynamic and interactive environment driven by the Google Gemini API."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  cloud_firestore: ^5.1.0
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.6
  custom_rating_bar: ^3.0.0
  device_preview: ^1.2.0
  firebase_auth: ^5.1.4
  firebase_core: ^3.2.0
  firebase_database: ^11.0.3
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.1.0
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.3
  google_sign_in: ^6.2.1
  http: ^1.2.2
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  intl: ^0.19.0
  ionicons: ^0.2.2
  logger: ^2.4.0
  lottie: ^3.1.2
  mobile_scanner: ^5.1.1
  outline_gradient_button: ^2.0.1+1
  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  qr_scanner_overlay: ^0.0.2
  share_plus: ^10.0.0
  syncfusion_flutter_sliders: ^26.1.42
  url_launcher: ^6.3.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/launcher_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/avatars/
    - assets/images/logo/
    - assets/lottie/
    